version: '3'

services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - '4200:80'

  backend:
    build: ./backend
    restart: always
    ports:
        - '8080:8080'
    depends_on:
      - postgresql

  postgresql:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: recipes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - '8888:8080'

volumes:
  postgresql_data: